### ISSUE TITLE
 xml/yml files

### ISSUE THREAD

**Issue by SabraHashemi** [pengx17/facedetect#1]
Hi,
I'm new to work, i want to hide .yml/.xml files in my project when i make an app,
I saw your code but cant understand how it work?
Please guide me how to run it and see its effects in this way
Thank you

**Comment by pengx17** [comment]
This project has not been maintained for a long time and I am not working on OpenCV projects any longer.
Not sure if it is working at the moment, but this app was designed to be built with CMake and link to the OpenCV package (perhaps OpenCV 2.4 ? I cannot remember ...).
